### ISSUE TITLE
(Suggestion) Improvements to directional particles and certain VFX

### ISSUE THREAD

**Issue by I0nTech** [elBukkit/EffectLib#10]
Title, directional particles summoned by setting:
```
  effects:
    circle:
      - location: origin
        effectlib:
          class: Vortex
          particle: end_rod
          radius: 4
          particles: 20
          particle_count: 0
          particle_offset_x: 0
          particle_offset_y: 1
          particle_offset_z: 0
          particle_data: 1
 ```

Can only travel in the x, y and z axes. This severely limits what can be done with directional particles as of now.
https://imgur.com/a/IQswZDT

Solution:
To effectlib, add relative_particle_offset_x, relative_particle_offset_y and relative_particle_offset_z, functioning the same way as relative_offset, but for particles. The particle would travel in the appropriate direction, when particle_count: 0 and particle data is supported.

This would also allow us to have more control over the way particles are summoned when using particle_offset.

(I honestly just want to be able to create particle shockwaves and flamethrower effects in Magic without needing to set a marker for or cast a MythicMobs skill just for VFX...)

If possible, allowing auto-orient: true to cause directional particles to travel in the direction from the source to target and having a dedicated directional: true parameter instead of particle_count: 0 would be great.
